# Header
menu:
  Home: /
  Archives: /archives
  About: /about
# Title on top left of menu. Leave empty to use main blog title
brand: Damon

# URL of the Home page image
index_cover: /img/home-bg.jpg
logo: /img/logo_yellow.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# baidu Analytics Tracking ID
ba_t_id:

# Google Analytics Tracking ID
ga_t_id:
ga_domain:


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

#Side avatar
gravatar:
  account: damonzhaifei@gmail.com
  size: 60
sidebar-about-description: '传说中的前端工程师 业余设计师 摄影爱好者'

# Social Accounts
sns_link:
  twitter:
  facebook:
  weixin:
  zhihu: http://zhuanlan.zhihu.com/jscss
  weibo: http://weibo.com/518057456/
  github: https://github.com/stephenzhao
# Friends
friends: [
    {
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]

